# Generated by Django 5.2.7 on 2025-12-08 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CLIENT', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientassessmenttype',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assessment_type', to='core.assessmenttype'),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CLIENT.clientaddress'),
        ),
        migrations.AddField(
            model_name='clientassessmenttype',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assessement', to='CLIENT.clientdetail'),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='CLIENT.clientdetail'),
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='CLIENT.clientassessmenttype'),
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='compliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.compilancetype'),
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clientassessmenttype',
            unique_together={('assessment_type', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='clientteam',
            unique_together={('company', 'email')},
        ),
    ]
