# Generated by Django 5.2.7 on 2025-12-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assessment_type', to='core.assessmenttype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assessement', to='CLIENT.clientdetail')),
            ],
            options={
                'unique_together': {('assesment_type', 'client')},
            },
        ),
    ]
