# Generated by Django 5.2.7 on 2025-12-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientteam',
            old_name='company',
            new_name='client',
        ),
        migrations.AlterUniqueTogether(
            name='clientteam',
            unique_together={('client', 'email')},
        ),
    ]
