# Generated by Django 5.2.7 on 2025-12-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0003_rename_company_clientteam_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmapping',
            old_name='client',
            new_name='client_assessment',
        ),
    ]
