# Generated by Django 5.2.7 on 2025-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0004_rename_client_urlmapping_client_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
