# Generated by Django 5.2.7 on 2025-12-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0005_urlmapping_is_completed'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='CLIENT.urlmapping')),
                ('vulnerability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vulnerabilities')),
            ],
            options={
                'unique_together': {('url', 'vulnerability')},
            },
        ),
    ]
